[package]
name = "rupert_parser"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[[bin]]
name = "rupert"
path = "main.rs"

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
