[package]
name = "rupert"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
rutils = { git = "ssh://github.com/vehmloewff/rutils", rev = "0.2.0" }
serde = { version = "1.0.197", features = ["derive"] }
